version: '3.9'

volumes:
  postgres:
    name: 'unicred-postgres'
  rabbitmq:
    name: 'unicred-rabbitmq'
  prometheus:
    name: 'unicred-prometheus'
  grafana:
    name: 'unicred-grafana'
  loki:
    name: 'unicred-loki'
  promtail:
    name: 'unicred-promtail'

services:
#  associado:
#    build:
#      context: ./associado
#      dockerfile: Dockerfile
#    hostname: associado-srv
#    restart: no
#    deploy:
#      resources:
#        limits:
#          cpus: '0.1'
#          memory: '200MB'
#    depends_on:
#      - postgres
#      - rabbitmq
#      - prometheus
#      - grafana
#    env_file:
#      - ./infra/envs/.env
#      - ./infra/envs/associado.env
#    network_mode: host

  rabbitmq:
    image: rabbitmq:3.12-management
    restart: always
    hostname: rabbitmq-srv
    env_file:
      - ./infra/envs/rabbitmq.env
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '300MB'
    expose:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    network_mode: host

  postgres:
    image: postgres:16.0
    restart: always
    hostname: postgres-srv
    env_file:
      - ./infra/envs/postgres.env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1200MB'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./infra/postgres/:/docker-entrypoint-initdb.d/
    network_mode: host

  adminer:
    image: adminer:latest
    restart: always
    hostname: adm-srv
    env_file:
      - ./infra/envs/adminer.env
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '15MB'
    network_mode: host

  prometheus:
    image: prom/prometheus:v2.47.0
    restart: always
    hostname: prometheus-srv
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '50MB'
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    network_mode: host

  grafana:
    image: grafana/grafana:10.1.2
    restart: always
    hostname: grafana-srv
    depends_on:
      - prometheus
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '300MB'
    env_file:
      - ./infra/envs/grafana.env
    volumes:
      # - ./infra/grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana:/var/lib/grafana
    network_mode: host

  loki:
    image: grafana/loki:2.9.1
    restart: always
    hostname: loki-srv
    depends_on:
      - grafana
    volumes:
#      - ./infra/grafana/loki.yaml:/etc/loki/local-config.yaml
      - loki:/etc/loki
    network_mode: host

  promtail:
    image: grafana/promtail:2.9.1
    restart: always
    hostname: promtail-srv
    depends_on:
      - loki
    volumes:
      - ./infra/grafana/promtail.yaml:/etc/promtail/config.yml
    network_mode: host

