#!/bin/sh

echo "Restarting..."

docker-compose down

docker volume rm unicred-postgres --force
docker volume rm unicred-rabbitmq --force
docker volume rm unicred-prometheus --force

docker-compose up rabbitmq postgres adminer prometheus
