version: '3.9'

services:
#  https://hub.docker.com/_/sonarqube

  rabbitmq:
    image: rabbitmq:3.12-management
    restart: always
    hostname: rabbitmq-srv
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      TZ: America/Sao_Paulo
    expose:
      - '5672:5672'
      - '15672:15672'
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      app:

  postgres:
    image: postgres:latest
    restart: always
    hostname: postgres-srv
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_MULTIPLE_DATABASES: associado,boleto,arquivo
      TZ: America/Sao_Paulo
      POSTGRES_TZDATA: /usr/share/zoneinfo/America/Sao_Paulo
    expose:
      - '5432'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    networks:
      app:

  adminer:
    image: adminer:latest
    restart: always
    hostname: adm-srv
    environment:
      ADMINER_DEFAULT_SERVER: postgres-srv
    ports:
      - '8080:8080'
    expose:
      - '8080'
    networks:
      app:

volumes:
  postgres:
    name: 'unicred-postgres'
  rabbitmq:
    name: 'unicred-rabbitmq'

networks:
  app:
