---
debug: true

server:
  shutdown: immediate
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
    include-stacktrace: always

spring:
  jpa:
    show-sql: true
  devtools:
    livereload:
      enabled: true
---
