---
debug: true

server:
  port: "${PORT:3000}"
  shutdown: immediate
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
    include-stacktrace: always

spring:
  jpa:
    show-sql: true
  devtools:
    livereload:
      enabled: true

logging:
  file:
    name: "${logging.file.path}/dev/${START_TIME}.log"
    path: "@project.basedir@/tmp/logs/${spring.application.name}/@project.version@"
---
