debug: false

server:
  port: "${PORT}"
  shutdown: graceful
  servlet:
    context-path: ""
  error:
    include-binding-errors: never
    include-exception: false
    include-message: never
    include-stacktrace: never

info:
  app:
    name: "@project.name@"
    version: "@project.version@"
    description: "@project.description@"

spring:
  application:
    name: "@project.name@"
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:}"
  main:
    banner-mode: off
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?${DATABASE_QUERY:}"
    name: "${DATABASE_NAME}"
    username: "${DATABASE_USERNAME}"
    password: "${DATABASE_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgresPlusDialect
  rabbitmq:
    host: "${RABBITMQ_HOST}"
    port: "${RABBITMQ_PORT}"
    username: "${RABBITMQ_USERNAME}"
    password: "${RABBITMQ_PASSWORD}"
    template:
      reply-timeout: "${RABBITMQ_REPLY_TIMEOUT}"
      receive-timeout: "${RABBITMQ_RECEIVE_TIMEOUT}"
  devtools:
    livereload:
      enabled: false
  flyway:
    enabled: true
    user: "${DATABASE_USERNAME}"
    password: "${DATABASE_PASSWORD}"
    url: "jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}"
    table: "migrations"
    driver-class-name: "org.postgresql.Driver"
    connect-retries: 3
    connect-retries-interval: "30s"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    url: "/swagger.yaml"
    disable-swagger-default-url: true

# https://docs.spring.io/spring-boot/docs/current/actuator-api/htmlsingle/#overview
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
        pushgateway:
          base-url: "${PROMETHEUS_PUSH_GATEWAY_URL}"
          enabled: "${PROMETHEUS_PUSH_GATEWAY_ENABLED}"
          push-rate: "30s"

custom-app-properties:
