debug: false

server:
  port: "${PORT}"
  shutdown: graceful
  servlet:
    context-path: ""
  error:
    include-binding-errors: never
    include-exception: false
    include-message: never
    include-stacktrace: never

spring:
  application:
    name: "app-associado"
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:}"
  main:
    banner-mode: off
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?${DATABASE_QUERY:}"
    name: "${DATABASE_NAME}"
    username: "${DATABASE_USERNAME}"
    password: "${DATABASE_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgresPlusDialect
  rabbitmq:
    host: "${RABBITMQ_HOST}"
    port: "${RABBITMQ_PORT}"
    username: "${RABBITMQ_USERNAME}"
    password: "${RABBITMQ_PASSWORD}"
    template:
      reply-timeout: "${RABBITMQ_REPLY_TIMEOUT}"
      receive-timeout: "${RABBITMQ_RECEIVE_TIMEOUT}"
  devtools:
    livereload:
      enabled: false
  flyway:
    enabled: true
    user: "${DATABASE_USERNAME}"
    password: "${DATABASE_PASSWORD}"
    url: "jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}"
    table: "migrations"
    driver-class-name: "org.postgresql.Driver"
    connect-retries: 3
    connect-retries-interval: "30s"

logging:
  level:
    com.example.associado: debug

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    url: "/swagger.yaml"
    disable-swagger-default-url: true

custom-app-properties:
