server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: 'system'
    pipeline_stages:
      - docker:
    static_configs:
      - targets:
          - 'localhost'
        labels:
          job: 'varlogs'
          __path__: '/var/log/*.log'

  - job_name: 'associado'
    static_configs:
      - targets:
          - 'localhost'
        labels:
          job: 'someone_service'
          host: 'yourhost'
          __path__: '/srv/log/associado/*.log'
